search_task:
  description: >
    Cerca l'argomento fornito dall'utente su Internet e restituisci i primi 3 URL più rilevanti.
  expected_output: >
    Una lista dei primi 3 URL trovati online relativi all'argomento.
  agent: web_agent

scrape_task:
  description: >
    Estrai e riassumi il contenuto dei primi 3 URL trovati nella ricerca precedente.
  expected_output: >
    Un riassunto chiaro e conciso dei contenuti dei 3 URL.
  agent: web_agent
  context:
    - search_task
